# Generated by Django 6.0.2 on 2026-05-07 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinace',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=80)),
                ('zeme', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'Destinace',
            },
        ),
        migrations.CreateModel(
            name='Zakaznici',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('jmeno', models.CharField(max_length=50)),
                ('prijmeni', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('ulice', models.CharField(max_length=50)),
                ('c_p', models.CharField(db_column='č.p.', max_length=10)),
                ('mesto', models.CharField(max_length=40)),
                ('psc', models.CharField(max_length=10)),
                ('stat', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Zákazníci',
            },
        ),
        migrations.CreateModel(
            name='Zajezdy',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('zacatek', models.DateField()),
                ('konec', models.DateField()),
                ('cena', models.IntegerField()),
                ('kapacita', models.IntegerField()),
                ('obsazeno', models.IntegerField()),
                ('doprava', models.CharField(max_length=30)),
                ('destination', models.ForeignKey(db_column='destination_id', on_delete=django.db.models.deletion.CASCADE, to='traveling_app.destinace')),
            ],
            options={
                'verbose_name_plural': 'Zájezdy',
            },
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('people', models.IntegerField()),
                ('cena', models.IntegerField()),
                ('stav', models.CharField(max_length=15)),
                ('platba', models.CharField(max_length=15)),
                ('trip', models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.CASCADE, to='traveling_app.zajezdy')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='traveling_app.zakaznici')),
            ],
            options={
                'verbose_name_plural': 'Rezervace',
            },
        ),
    ]
