# Generated by Django 6.0.2 on 2026-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveling_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zajezdy',
            name='typ_dovolene',
            field=models.CharField(default='Pobytový', max_length=50, verbose_name='Typ dovolené'),
        ),
    ]
